### PR TITLE
Migrated to Flixel 5.5.0 , OpenFL 9.3.2, Lime 8.1.1, djflixel 0.5.8

### PR DESCRIPTION
**Pull request by thecocce**

### CODE REVIEW

**Comment by john32b** [comment]
hey you updated the code, many thanks! 
I saw you fork this the other day and then made a quick push with the assets
*(I was afraid this would get taken down since the old game got a steam release as soon as I published this)* anyway,

Currently I am on a laptop with no haxe/flixel dev environment, as soon as I install things and look into the code to make sure it works I will merge this

cheers :smile:

**Comment by john32b** [comment]
hey, I took a look, and oh my god! it compiles ok but the new haxeflixel version seems to break everything.
first of all the crt shader got zoomed in, and in html5 all the text placement is wrong.
Could it be me? I built for hashlink and html5, don't have time for native build, I am on a slower laptop currently :crying_cat_face: 
Also, huge crash when you enter the pause menu.

## current version shader is fine
old

## new haxeflixel, shader wrong, misaligned 
new

Did this thing work ok for you? What targets did you build, what OS?

also I am sure that djFlixel is to blame for most of these since it gave me lots of warnings and a few errors when I compiled the djFlixel demo.

first I am going to work on djFlixel, make sure it builds ok,
and then I'll take a look into the shader and pause crashing things, but on the slow burner, so don't sweat anything.

I'll leave this PR open

**Comment by thecocce** [comment]
Hi, I m using Windows 11. I tried target Flash (with no shaders), html5 and Hashlink.

My haxelib env:
`haxelib list`

`djA: [git]`
`djFlixel: [git]`
`flixel: [5.5.0]`
`hashlink: [0.1.0]`
`lime: [8.1.1]`
`openfl: [9.3.2]`

html5 target (tested on Firefox, Chromium)

Windows-Firefox-FutureKnightDX – Mozilla Firefox

HashLink

Windows-HashLink-FutureKnightDX

**Comment by john32b** [comment]
oh, your HTML target seems to be rendering the text correctly, 
so it is something on my end for the html, going to re-check it,
I have the same library versions, but I do run from debian, I don't think thats it? could it be? :worried: 
are you getting the crash when you open the pause menu from gameplay?

and yes the shader is wrong, the scanlines should be shorter, it seems like it is zoomed in at 2x.
I'll take a look at the shader later.

**Comment by thecocce** [comment]
Hi, I have same problem on access pause menu.

```
Uncaught exception: Null access .length
Called from flixel.tweens.misc.VarTween.isTweenOf(flixel/tweens/misc/VarTween.hx:123)
Called from flixel.tweens.FlxTweenManager.forEachTweensOf(flixel/tweens/FlxTween.hx:1415)
Called from flixel.tweens.FlxTweenManager.cancelTweensOf(flixel/tweens/FlxTween.hx:1357)
Called from flixel.tweens.$FlxTween.cancelTweensOf(flixel/tweens/FlxTween.hx:467)
Called from djFlixel.ui.menu.MCursor.point(djFlixel/ui/menu/MCursor.hx:146)
```

**Comment by thecocce** [comment]
The shader now should works. Error was due to FlxG.initial Zoom is removed

**Review by thecocce — COMMENTED** [review]
Update correct djflixel version, applied linter on markdown readme

**Comment by john32b** [comment]
Just checked it, oh it was a simple fix for the shader, didn't have the time to properly take a deep dive at the code.

I am going to work on the djflixel library, and once I update it and push it, I will then merge this, so that the master branch can compile and work with no issues.

Thanks!

**Comment by john32b** [comment]
finally got around to looking at this. I fixed the main menu crashing thing over at djflixel,
also the new lib versions seemed to fix the font metrics on html5, I pushed an update to master.

**Comment by thecocce** [comment]
Nice news. Tell me if you need some help.

**Pull request merged**
